- name: Configure alloy config directory
  ansible.builtin.file:
    path: /etc/alloy/config.d
    state: directory
    mode: '755'
  become: true

- name: Configure alloy to send logs to central Loki server
  ansible.builtin.template:
    src: journald.alloy.j2
    dest: /etc/alloy/config.d/journald.alloy
    mode: '644'
  become: true
  notify: "restart alloy"

- name: Deploy Alloy to send logs to central Loki server
  ansible.builtin.include_role:
    name: grafana.grafana.alloy
  vars:
    alloy_env_file_vars:
      CONFIG_FILE: /etc/alloy/config.d

- name: Correct alloy config ownership
  ansible.builtin.file:
    path: "{{ alloy_config.path }}"
    state: "{{ alloy_config.type }}"
    owner: 'alloy'
    group: 'alloy'
  loop:
    - path: /etc/alloy/config.d
      type: directory
    - path: /etc/alloy/config.d/journald.alloy
      type: file
  loop_control:
    loop_var: alloy_config
  become: true

